# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenPGP/ui/display_keyrings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from OpenPGP.asymmetric_encryption.keys.privatekeyring import private_keyring
from OpenPGP.asymmetric_encryption.keys.publickeyring import public_keyring
from OpenPGP.asymmetric_encryption.keys import utilities
from OpenPGP.users.users_db import usersDB

class Ui_display_keyrings_window(object):

    def load_private_keyring(self):
        row = 0
        logged_in_userID = usersDB.logged_in_user.name + ":" + usersDB.logged_in_user.email
        self.private_keyring_table.setRowCount(len(private_keyring.get_keys_by_userID(logged_in_userID)))

        for key in private_keyring.get_keys_by_userID(logged_in_userID):
            self.private_keyring_table.setItem(row, 0, QtWidgets.QTableWidgetItem(str(key.timestamp)))
            self.private_keyring_table.setItem(row, 1, QtWidgets.QTableWidgetItem(str(key.keyID)))
            self.private_keyring_table.setItem(row, 2, QtWidgets.QTableWidgetItem(key.repr_public_key()))
            self.private_keyring_table.setItem(row, 3, QtWidgets.QTableWidgetItem(str(key.encrypted_private_key)))
            self.private_keyring_table.setItem(row, 4, QtWidgets.QTableWidgetItem(str(key.userID)))
            row += 1

        self.private_keyring_table.resizeColumnsToContents()

    def load_public_keyring(self):
        row = 0
        logged_in_userID = usersDB.logged_in_user.name + ":" + usersDB.logged_in_user.email
        self.public_keyring_table.setRowCount(len(public_keyring.get_keys_by_userID(logged_in_userID)))

        for key in public_keyring.get_keys_by_userID(logged_in_userID):
            self.public_keyring_table.setItem(row, 0, QtWidgets.QTableWidgetItem(str(key.timestamp)))
            self.public_keyring_table.setItem(row, 1, QtWidgets.QTableWidgetItem(str(key.keyID)))
            self.public_keyring_table.setItem(row, 2, QtWidgets.QTableWidgetItem(key.repr_public_key()))
            self.public_keyring_table.setItem(row, 3, QtWidgets.QTableWidgetItem(str(key.userID)))
            row += 1

        self.public_keyring_table.resizeColumnsToContents()

    def setupUi(self, display_keyrings_window):
        display_keyrings_window.setObjectName("display_keyrings_window")
        display_keyrings_window.resize(1154, 949)
        self.centralwidget = QtWidgets.QWidget(display_keyrings_window)
        self.centralwidget.setObjectName("centralwidget")
        self.private_keyring_table = QtWidgets.QTableWidget(self.centralwidget)
        self.private_keyring_table.setGeometry(QtCore.QRect(30, 80, 1101, 351))
        self.private_keyring_table.setObjectName("private_keyring_table")
        self.private_keyring_table.setColumnCount(5)
        self.private_keyring_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.private_keyring_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.private_keyring_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.private_keyring_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.private_keyring_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.private_keyring_table.setHorizontalHeaderItem(4, item)
        self.public_keyring_table = QtWidgets.QTableWidget(self.centralwidget)
        self.public_keyring_table.setGeometry(QtCore.QRect(30, 510, 1101, 371))
        self.public_keyring_table.setObjectName("public_keyring_table")
        self.public_keyring_table.setColumnCount(4)
        self.public_keyring_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.public_keyring_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.public_keyring_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.public_keyring_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.public_keyring_table.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 470, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        display_keyrings_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(display_keyrings_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1154, 26))
        self.menubar.setObjectName("menubar")
        display_keyrings_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(display_keyrings_window)
        self.statusbar.setObjectName("statusbar")
        display_keyrings_window.setStatusBar(self.statusbar)

        self.load_private_keyring()
        self.load_public_keyring()

        self.retranslateUi(display_keyrings_window)
        QtCore.QMetaObject.connectSlotsByName(display_keyrings_window)

    def retranslateUi(self, display_keyrings_window):
        _translate = QtCore.QCoreApplication.translate
        display_keyrings_window.setWindowTitle(_translate("display_keyrings_window", "MainWindow"))
        item = self.private_keyring_table.horizontalHeaderItem(0)
        item.setText(_translate("display_keyrings_window", "Timestamp"))
        item = self.private_keyring_table.horizontalHeaderItem(1)
        item.setText(_translate("display_keyrings_window", "Key ID"))
        item = self.private_keyring_table.horizontalHeaderItem(2)
        item.setText(_translate("display_keyrings_window", "Public key"))
        item = self.private_keyring_table.horizontalHeaderItem(3)
        item.setText(_translate("display_keyrings_window", "Encrypted private key"))
        item = self.private_keyring_table.horizontalHeaderItem(4)
        item.setText(_translate("display_keyrings_window", "User ID"))
        item = self.public_keyring_table.horizontalHeaderItem(0)
        item.setText(_translate("display_keyrings_window", "Timestamp"))
        item = self.public_keyring_table.horizontalHeaderItem(1)
        item.setText(_translate("display_keyrings_window", "Key ID"))
        item = self.public_keyring_table.horizontalHeaderItem(2)
        item.setText(_translate("display_keyrings_window", "Public key"))
        item = self.public_keyring_table.horizontalHeaderItem(3)
        item.setText(_translate("display_keyrings_window", "User ID"))
        self.label.setText(_translate("display_keyrings_window", "Private keyring"))
        self.label_2.setText(_translate("display_keyrings_window", "Public keyring"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    display_keyrings_window = QtWidgets.QMainWindow()
    ui = Ui_display_keyrings_window()
    ui.setupUi(display_keyrings_window)
    display_keyrings_window.show()
    sys.exit(app.exec_())
