# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\OpenPGP\ui\login_register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from OpenPGP.users.users_db import usersDB
from OpenPGP.users.user import User
from main_window import Ui_main_window

class Ui_login_register_window(object):

    def __init__(self):
        self.login_register_window = None

    def login(self):
        usersDB.logged_in_user = usersDB.login(self.login_email.text(), self.login_password.text())
        if usersDB.logged_in_user is None:
            self.login_error.setText("Ne postoji takav korisnik")
            return

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_main_window()
        self.ui.setupUi(self.window)
        self.window.show()
        if self.login_register_window:
            self.login_register_window.close()

    def register(self):
        if self.register_name.text() == "" or self.register_email.text() == "" or self.register_password.text() == "":
            self.registration_error.setText("Sva polja su obavezna.")
            return

        if self.register_email.text() in usersDB.users:
            self.registration_error.setText("Korisnik sa tim emailom vec postoji")
            return

        usersDB.register(self.register_name.text(), self.register_email.text(), self.register_password.text())

        self.registration_error.setText("Uspesna registracija")

    def setupUi(self, login_register_window):
        self.login_register_window = login_register_window
        login_register_window.setObjectName("login_register_window")
        login_register_window.resize(864, 634)
        self.login_email = QtWidgets.QLineEdit(login_register_window)
        self.login_email.setGeometry(QtCore.QRect(80, 170, 251, 31))
        self.login_email.setObjectName("login_email")
        self.login_password = QtWidgets.QLineEdit(login_register_window)
        self.login_password.setGeometry(QtCore.QRect(80, 260, 251, 31))
        self.login_password.setObjectName("login_password")
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_name = QtWidgets.QLineEdit(login_register_window)
        self.register_name.setGeometry(QtCore.QRect(510, 170, 251, 31))
        self.register_name.setObjectName("register_name")
        self.register_email = QtWidgets.QLineEdit(login_register_window)
        self.register_email.setGeometry(QtCore.QRect(510, 260, 251, 31))
        self.register_email.setObjectName("register_email")
        self.register_password = QtWidgets.QLineEdit(login_register_window)
        self.register_password.setGeometry(QtCore.QRect(510, 350, 251, 31))
        self.register_password.setObjectName("register_password")
        self.register_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label = QtWidgets.QLabel(login_register_window)
        self.label.setGeometry(QtCore.QRect(80, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login_register_window)
        self.label_2.setGeometry(QtCore.QRect(80, 230, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.login_button = QtWidgets.QPushButton(login_register_window, clicked=lambda: self.login())
        self.login_button.setGeometry(QtCore.QRect(130, 340, 141, 41))
        self.login_button.setObjectName("login_button")
        self.label_3 = QtWidgets.QLabel(login_register_window)
        self.label_3.setGeometry(QtCore.QRect(510, 230, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(login_register_window)
        self.label_4.setGeometry(QtCore.QRect(510, 320, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(login_register_window)
        self.label_5.setGeometry(QtCore.QRect(510, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.register_button = QtWidgets.QPushButton(login_register_window, clicked=lambda: self.register())
        self.register_button.setGeometry(QtCore.QRect(560, 430, 141, 51))
        self.register_button.setObjectName("register_button")
        self.label_6 = QtWidgets.QLabel(login_register_window)
        self.label_6.setGeometry(QtCore.QRect(500, 580, 331, 20))
        self.label_6.setObjectName("label_6")
        self.login_error = QtWidgets.QLabel(login_register_window)
        self.login_error.setGeometry(QtCore.QRect(80, 310, 241, 16))
        self.login_error.setText("")
        self.login_error.setObjectName("login_error")
        self.registration_error = QtWidgets.QLabel(login_register_window)
        self.registration_error.setGeometry(QtCore.QRect(510, 400, 241, 16))
        self.registration_error.setText("")
        self.registration_error.setObjectName("registration_error")

        self.retranslateUi(login_register_window)
        QtCore.QMetaObject.connectSlotsByName(login_register_window)

    def retranslateUi(self, login_register_window):
        _translate = QtCore.QCoreApplication.translate
        login_register_window.setWindowTitle(_translate("login_register_window", "Form"))
        self.label.setText(_translate("login_register_window", "Email:"))
        self.label_2.setText(_translate("login_register_window", "Password:"))
        self.login_button.setText(_translate("login_register_window", "Login"))
        self.label_3.setText(_translate("login_register_window", "Email:"))
        self.label_4.setText(_translate("login_register_window", "Password:"))
        self.label_5.setText(_translate("login_register_window", "Name:"))
        self.register_button.setText(_translate("login_register_window", "Register"))
        self.label_6.setText(_translate("login_register_window", "Milica Cvetkovic 2020/0003 | Zeljko Urosevic 2020/0073"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_register_window = QtWidgets.QWidget()
    ui = Ui_login_register_window()
    ui.setupUi(login_register_window)
    login_register_window.show()
    sys.exit(app.exec_())
