# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenPGP/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from generate_delete_window import Ui_generate_delete_window
from display_keyrings_window import Ui_display_keyrings_window
from send_message_window import Ui_send_message_window
from OpenPGP.users.users_db import usersDB
from import_export_window import Ui_import_export_window
from receive_message_window import Ui_receive_message_window

class Ui_main_window(object):

    def __init__(self):
        self.main_window = None

    def open_generate_delete_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_generate_delete_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_display_keyrings_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_display_keyrings_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_send_message_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_send_message_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_receive_message_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_receive_message_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_import_export_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_import_export_window()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout(self):
        from login_register_window import Ui_login_register_window
        usersDB.logged_in_user = None
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_login_register_window()
        self.ui.setupUi(self.window)
        self.window.show()
        if self.main_window:
            self.main_window.close()


    def setupUi(self, main_window):
        self.main_window =  main_window
        main_window.setObjectName("main_window")
        main_window.resize(800, 444)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 160, 641, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(50, 0, 50, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keyrings_button = QtWidgets.QPushButton(self.verticalLayoutWidget,clicked=lambda: self.open_display_keyrings_window())
        self.keyrings_button.setObjectName("keyrings_button")
        self.verticalLayout.addWidget(self.keyrings_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 240, 641, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.send_button = QtWidgets.QPushButton(self.horizontalLayoutWidget, clicked=lambda: self.open_send_message_window())
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.receive_button = QtWidgets.QPushButton(self.horizontalLayoutWidget, clicked=lambda: self.open_receive_message_window())
        self.receive_button.setObjectName("receive_button")
        self.horizontalLayout.addWidget(self.receive_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 80, 641, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.generate_delete_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2,
                                                            clicked=lambda: self.open_generate_delete_window())
        self.generate_delete_button.setObjectName("generate_delete_button")
        self.horizontalLayout_2.addWidget(self.generate_delete_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.import_export_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2,
                                                          clicked=lambda: self.open_import_export_window())
        self.import_export_button.setObjectName("import_export_button")
        self.horizontalLayout_2.addWidget(self.import_export_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 340, 321, 39))
        self.label_2.setObjectName("label_2")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setObjectName("logout_button")
        self.logout_button.setGeometry(QtCore.QRect(700, 15, 70, 30))
        self.logout_button.clicked.connect(lambda : self.logout())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Zastita podataka"))
        self.keyrings_button.setText(_translate("main_window", "Display keyrings"))
        self.send_button.setText(_translate("main_window", "Send message"))
        self.receive_button.setText(_translate("main_window", "Receive message"))
        self.logout_button.setText(_translate("main_window", "Log out"))
        self.generate_delete_button.setText(_translate("main_window", "Generate and delete keys"))
        self.import_export_button.setText(_translate("main_window", "Import and export keys"))
        self.label.setText(_translate("main_window", f"Hello {usersDB.logged_in_user.name}!"))
        self.label_2.setText(_translate("main_window", "Milica Cvetkovic 2020/0003 | Zeljko Urosevic 2020/0073"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
