
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 12 15:27:59 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 38;
  public static final int RIGHT_BRACKET = 40;
  public static final int INCREMENT = 31;
  public static final int CHAR = 48;
  public static final int CONST = 6;
  public static final int ASTERISK = 20;
  public static final int EQUALS = 44;
  public static final int LOGICAL_NOT_EQUALS = 24;
  public static final int NAMESPACE = 17;
  public static final int SLASH = 21;
  public static final int GREATER = 26;
  public static final int CONTINUE = 14;
  public static final int LESS = 28;
  public static final int FOR = 15;
  public static final int MINUS = 19;
  public static final int DECREMENT = 32;
  public static final int STATIC = 16;
  public static final int SEMICOLON = 33;
  public static final int BOOL = 46;
  public static final int LEFT_BRACE = 41;
  public static final int COMMA = 35;
  public static final int CLASS = 4;
  public static final int PLUS = 18;
  public static final int GREATER_OR_EQUALS = 25;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int LOGICAL_OR = 30;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 22;
  public static final int RIGHT_BRACE = 42;
  public static final int NUMBER = 45;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int FOREACH = 43;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int DOUBLE_COLON = 34;
  public static final int LOGICAL_AND = 29;
  public static final int EXTENDS = 13;
  public static final int LEFT_PAREN = 37;
  public static final int LOGICAL_EQUALS = 23;
  public static final int LESS_OR_EQUALS = 27;
  public static final int LEFT_BRACKET = 39;
  public static final int PRINT = 9;
}

