/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Olympiad_Olympiad */

#ifndef _Included_Olympiad_Olympiad
#define _Included_Olympiad_Olympiad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Olympiad_Olympiad
 * Method:    evaluateNumber
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Olympiad_Olympiad_evaluateNumber
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     Olympiad_Olympiad
 * Method:    average
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_Olympiad_Olympiad_average
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     Olympiad_Olympiad
 * Method:    nativeNumberCompetitorsByCountry
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Olympiad_Olympiad_nativeNumberCompetitorsByCountry
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     Olympiad_Olympiad
 * Method:    nativeNumberDisciplinesByYearSeason
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Olympiad_Olympiad_nativeNumberDisciplinesByYearSeason
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Olympiad_Olympiad
 * Method:    nativeAvgByYearSeason
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Olympiad_Olympiad_nativeAvgByYearSeason
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
